import type { DocumentNode, ValueNode } from '../parser/ast.js';
import { mkdir, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';

export interface EmittedFile {
  path: string;        // relative to .gdl-out/
  contents: string;
}

export interface EmitOptions {
  extensionVersion?: string;
}

/** Render a string value as a single-quoted TS string literal. */
const sq = (s: string | number | boolean): string => {
  if (typeof s !== 'string') return JSON.stringify(s);
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
};

const renderValueNode = (v: ValueNode): string => {
  if (v.kind === 'literal') {
    return `{ kind: 'literal', raw: ${sq(v.raw)} }`;
  }
  if (v.kind === 'interpolated') {
    return `{ kind: 'interpolated', template: ${sq(v.template)} }`;
  }
  if (v.kind === 'hookRef') {
    // hookRefs only appear in discovery.version today (Task 14 wires that path).
    // If a context: binding or modType.path ever uses !hook, we want this to throw loudly.
    throw new Error(`hookRef value (${v.hookId}) is not allowed in this position — only discovery.version accepts !hook in Plan 2`);
  }
  // Branch tag.
  const arms = Object.entries(v.arms)
    .map(([k, arm]) => `${sq(k)}: ${renderValueNode(arm)}`)
    .join(', ');
  return `{ kind: ${sq(v.kind)}, arms: { ${arms} }, default: ${renderValueNode(v.default)} }`;
};

const HEADER = `// AUTO-GENERATED by GDL. Do not edit by hand.
// Source: \${file}
`;

const banner = (file: string) => HEADER.replace('${file}', file);

export const emit = (doc: DocumentNode, opts: EmitOptions = {}): EmittedFile[] => {
  const bindings = (doc.context?.bindings ?? [])
    .map(b => `      { name: ${sq(b.name)}, value: ${renderValueNode(b.value)} }`)
    .join(',\n');

  const modTypes = (doc.modTypes ?? [])
    .map(mt => `      { id: ${sq(mt.id)}, name: ${sq(mt.name)}, path: ${renderValueNode(mt.path)} }`)
    .join(',\n');

  const stores = (doc.stores?.entries ?? [])
    .map(s => `      { id: ${sq(s.id)}, value: ${sq(s.value)} }`)
    .join(',\n');

  const reqFiles = `[${doc.game.requiredFiles.map(sq).join(', ')}]`;

  const extension = `${banner(doc.game.span.file)}
import { GdlRuntime } from '@gdl/runtime';
import type { IExtensionContext } from 'vortex-api';

export default function main(api: IExtensionContext): boolean {
  const runtime = new GdlRuntime(api);
  runtime.registerGame(
    {
      id: ${sq(doc.game.id)},
      name: ${sq(doc.game.name)},
      executable: ${sq(doc.game.executable)},
      requiredFiles: ${reqFiles},
      ${doc.game.logo ? `logo: ${sq(doc.game.logo)},` : ''}
      ${doc.game.contributedBy ? `contributedBy: ${sq(doc.game.contributedBy)},` : ''}
    },
    [
${stores}
    ],
    {
      bindings: [
${bindings}
      ],
    },
    [
${modTypes}
    ],
  );
  return true;
}
`;

  const info = JSON.stringify({
    id: doc.game.id,
    name: doc.game.name,
    version: opts.extensionVersion ?? '0.0.0',
    description: `Vortex extension for ${doc.game.name} (generated by GDL).`,
  }, null, 2);

  return [
    { path: 'extension.ts', contents: extension },
    { path: 'info.json',    contents: info },
  ];
};

export const writeEmittedFiles = async (cwd: string, files: EmittedFile[]): Promise<void> => {
  const outDir = join(cwd, '.gdl-out');
  await mkdir(outDir, { recursive: true });
  for (const f of files) {
    const dest = join(outDir, f.path);
    await mkdir(dirname(dest), { recursive: true });
    await writeFile(dest, f.contents, 'utf8');
  }
};
