import type {
  DocumentNode, ValueNode,
  InstallerNode, PatternNode, PredicateNode, TakeStrategy,
  ComparisonExpr, ValueRef,
  ToolbarActionNode,
} from '../parser/ast.js';
import { mkdir, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { buildSourceMap, type LineMapping } from './source-map.js';
import { renderTestsFile } from './tests-emit.js';

export interface EmittedFile {
  path: string;        // relative to .gdl-out/
  contents: string;
}

export interface EmitOptions {
  extensionVersion?: string;
}

/** Render a string value as a single-quoted TS string literal. */
export const sq = (s: string | number | boolean): string => {
  if (typeof s !== 'string') return JSON.stringify(s);
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
};

const renderValueNode = (v: ValueNode): string => {
  if (v.kind === 'literal') {
    return `{ kind: 'literal', raw: ${sq(v.raw)} }`;
  }
  if (v.kind === 'interpolated') {
    return `{ kind: 'interpolated', template: ${sq(v.template)} }`;
  }
  if (v.kind === 'hookRef') {
    // hookRefs only appear in discovery.version today (Task 14 wires that path).
    // If a context: binding or modType.path ever uses !hook, we want this to throw loudly.
    throw new Error(`hookRef value (${v.hookId}) is not allowed in this position — only discovery.version accepts !hook in Plan 2`);
  }
  // Branch tag.
  const arms = Object.entries(v.arms)
    .map(([k, arm]) => `${sq(k)}: ${renderValueNode(arm)}`)
    .join(', ');
  return `{ kind: ${sq(v.kind)}, arms: { ${arms} }, default: ${renderValueNode(v.default)} }`;
};

const renderPattern = (p: PatternNode): string =>
  `{ kind: '${p.kind}', pattern: ${sq(p.pattern)} }`;

const renderTake = (t: TakeStrategy): string => {
  if (typeof t === 'string') return sq(t);
  return `{ depth: ${t.depth} }`;
};

const renderRef = (r: ValueRef): string => {
  if (r.kind === 'literal') return `{ kind: 'literal', raw: ${JSON.stringify(r.raw)} }`;
  return `{ kind: 'ref', name: ${sq(r.name)} }`;
};

const renderComparison = (e: ComparisonExpr): string => {
  if (e.op === 'in') {
    return `{ op: 'in', left: ${renderRef(e.left)}, right: [${e.right.map(renderRef).join(', ')}] }`;
  }
  return `{ op: ${sq(e.op)}, left: ${renderRef(e.left)}, right: ${renderRef(e.right)} }`;
};

const renderPredicate = (p: PredicateNode): string => {
  if (p.kind === 'hasFile') return `{ kind: 'hasFile', glob: ${sq(p.pattern.pattern)} }`;
  if (p.kind === 'hasFiles') {
    const globs = p.patterns.map(pat => sq(pat.pattern)).join(', ');
    return `{ kind: 'hasFiles', globs: [${globs}] }`;
  }
  if (p.kind === 'matches') return `{ kind: 'matches', regex: ${sq(p.pattern.pattern)} }`;
  if (p.kind === 'when') return `{ kind: 'when', expr: ${renderComparison(p.expr)} }`;
  if (p.kind === 'any')  return `{ kind: 'any', arms: [${p.arms.map(renderPredicate).join(', ')}] }`;
  if (p.kind === 'all')  return `{ kind: 'all', arms: [${p.arms.map(renderPredicate).join(', ')}] }`;
  return `{ kind: 'not', arm: ${renderPredicate(p.arm)} }`;
};

const renderPlaceAt = (v: ValueNode): string => {
  if (v.kind === 'literal')      return sq(String(v.raw));
  if (v.kind === 'interpolated') return sq(v.template);
  throw new Error(`unsupported placeAt kind \`${v.kind}\` — lift branch/hook values into a context: binding and reference the binding`);
};

const renderInstaller = (inst: InstallerNode): string => {
  const parts: string[] = [
    `id: ${sq(inst.id)}`,
    `priority: ${inst.priority}`,
    `when: ${renderPredicate(inst.when)}`,
  ];
  if (inst.unless !== undefined) {
    parts.push(`unless: ${renderPredicate(inst.unless)}`);
  }
  if (inst.scope?.stores && inst.scope.stores.length > 0) {
    const storesLit = inst.scope.stores.map(s => sq(s)).join(', ');
    parts.push(`scope: { stores: [${storesLit}] }`);
  }
  if (inst.single) {
    parts.push(`single: { anchor: ${renderPattern(inst.single.anchor)}, take: ${renderTake(inst.single.take)}, placeAt: ${renderPlaceAt(inst.single.placeAt)} }`);
    parts.push(`modType: ${sq(inst.modType ?? '')}`);
  } else if (inst.route) {
    const routeStr = inst.route.map(r =>
      `{ match: ${renderPattern(r.match)}, anchor: ${renderPattern(r.anchor)}, take: ${renderTake(r.take)}, placeAt: ${renderPlaceAt(r.placeAt)}, modType: ${sq(r.modType)} }`
    ).join(', ');
    parts.push(`route: [${routeStr}]`);
  }
  return `{ ${parts.join(', ')} }`;
};

const renderToolbarAction = (a: ToolbarActionNode): string =>
  `{ id: ${sq(a.id)}, title: ${sq(a.title)}, priority: ${a.priority}, target: { kind: ${sq(a.target.kind)}, template: ${sq(a.target.template)} } }`;

const HEADER = `// AUTO-GENERATED by GDL. Do not edit by hand.
// Source: \${file}
`;

const banner = (file: string) => HEADER.replace('${file}', file);

export const emit = (doc: DocumentNode, opts: EmitOptions = {}): EmittedFile[] => {
  const bindings = (doc.context?.bindings ?? [])
    .map(b => `      { name: ${sq(b.name)}, value: ${renderValueNode(b.value)} }`)
    .join(',\n');

  const modTypes = (doc.modTypes ?? [])
    .map(mt => `      { id: ${sq(mt.id)}, name: ${sq(mt.name)}, path: ${renderValueNode(mt.path)} }`)
    .join(',\n');

  const installers = (doc.installers ?? [])
    .map(inst => `      ${renderInstaller(inst)}`)
    .join(',\n');

  const toolbarActions = (doc.toolbarActions ?? [])
    .map(a => `      ${renderToolbarAction(a)}`)
    .join(',\n');

  const setupDirsLines = (doc.setup?.ensureDirs ?? [])
    .map(d => `      ${sq(d)}`)
    .join(',\n');

  const didDeployRef = doc.events?.didDeploy?.hookId;
  const eventHooksBody = didDeployRef
    ? `      didDeploy: ${didDeployRef},`
    : '';

  const hookIds = new Set<string>();
  if (doc.discovery?.version) hookIds.add(doc.discovery.version.hookId);
  const hookImports = hookIds.size
    ? `import * as hooks from '../src/hooks.js';`
    : '';

  const eventHookImports: string[] = [];
  if (didDeployRef) eventHookImports.push(didDeployRef);
  const eventHooksImportLine = eventHookImports.length > 0
    ? `import { ${eventHookImports.join(', ')} } from '../src/hooks.js';`
    : '';

  const versionHook = doc.discovery?.version
    ? `hooks.${doc.discovery.version.hookId}`
    : 'undefined';

  const stores = (doc.stores?.entries ?? [])
    .map(s => `      { id: ${sq(s.id)}, value: ${sq(s.value)} }`)
    .join(',\n');

  const reqFiles = `[${doc.game.requiredFiles.map(sq).join(', ')}]`;

  const installersFile = `${banner(doc.game.span.file)}
import type { InstallerRule } from '@gdl/runtime';

export const rules: InstallerRule[] = [
${installers}
];
`;

  const testsFile = renderTestsFile(doc);

  const extension = `${banner(doc.game.span.file)}
import { GdlRuntime } from '@gdl/runtime';
import type { IExtensionContext } from 'vortex-api';
import { rules } from './installers.gen.js';
${hookImports}
${eventHooksImportLine}
export default function main(api: IExtensionContext): boolean {
  const runtime = new GdlRuntime(api);
  runtime.registerGame(
    {
      id: ${sq(doc.game.id)},
      name: ${sq(doc.game.name)},
      executable: ${sq(doc.game.executable)},
      requiredFiles: ${reqFiles},
      ${doc.game.logo ? `logo: ${sq(doc.game.logo)},` : ''}
      ${doc.game.contributedBy ? `contributedBy: ${sq(doc.game.contributedBy)},` : ''}
    },
    [
${stores}
    ],
    {
      bindings: [
${bindings}
      ],
    },
    [
${modTypes}
    ],
    rules,
    {
      versionHook: ${versionHook},
    },
    [
${toolbarActions}
    ],
    [
${setupDirsLines}
    ],
    {
${eventHooksBody}
    },
  );
  return true;
}
`;

  const info = JSON.stringify({
    id: doc.game.id,
    name: doc.game.name,
    version: opts.extensionVersion ?? '0.0.0',
    description: `Vortex extension for ${doc.game.name} (generated by GDL).`,
  }, null, 2);

  const lineMappings: LineMapping[] = [
    { generatedLine: 1, yamlLine: doc.game.span.line, yamlColumn: doc.game.span.column },
    ...(doc.installers ?? []).map((inst, i) => ({
      generatedLine: 6 + i,
      yamlLine: inst.span.line,
      yamlColumn: inst.span.column,
    })),
  ];
  const map = buildSourceMap('extension.ts', doc.game.span.file, lineMappings);
  const extensionWithMapRef = extension + `\n//# sourceMappingURL=extension.ts.map\n`;

  const files: EmittedFile[] = [
    { path: 'extension.ts',      contents: extensionWithMapRef },
    { path: 'extension.ts.map',  contents: JSON.stringify(map) },
    { path: 'installers.gen.ts', contents: installersFile },
    { path: 'info.json',         contents: info },
  ];
  if (testsFile) {
    files.push({ path: 'tests.gen.ts', contents: testsFile });
  }
  return files;
};

export const writeEmittedFiles = async (cwd: string, files: EmittedFile[]): Promise<void> => {
  const outDir = join(cwd, '.gdl-out');
  await mkdir(outDir, { recursive: true });
  for (const f of files) {
    const dest = join(outDir, f.path);
    await mkdir(dirname(dest), { recursive: true });
    await writeFile(dest, f.contents, 'utf8');
  }
};
