// Emits `.gdl-out/lifecycle.gen.ts`: vitest cases that drive the bundled
// extension through Vortex's lifecycle for every store declared in `stores:`,
// then assert the *exact* resolved paths setup creates and queryModPath
// returns. Pre-computed at codegen time using the same resolver the runtime
// uses, so the generated test is a literal pin against expected values — any
// drift in either game.yaml templates OR the runtime resolver fails the test
// with a clear diff.
//
// Also emits an end-to-end event-hook check when events.didDeploy is declared:
// spies on the hook export, fires the corresponding Vortex event, asserts the
// hook was actually invoked. Catches misnamed exports, mis-wired events, and
// regressions where the listener gets stripped from the runtime.
//
// Replaces ~108 lines of hand-rolled lifecycle.test.ts in each game extension.

import type { DocumentNode, ValueNode } from '../parser/ast.js';
import type { ContextSpec, DiscoveryFacts, ResolvableValue } from '../runtime/context-resolver.js';
import { resolveContext } from '../runtime/context-resolver.js';
import { interpolate } from '../runtime/interpolate.js';
import { sq } from './emit.js';

// AST ValueNode → runtime ResolvableValue. The AST type is a superset
// (includes hookRef which isn't valid in a context binding); strip those and
// throw if encountered.
const astToResolvable = (v: ValueNode): ResolvableValue => {
  if (v.kind === 'literal') return { kind: 'literal', raw: v.raw };
  if (v.kind === 'interpolated') return { kind: 'interpolated', template: v.template };
  if (v.kind === 'hookRef') {
    throw new Error(`hookRef ${v.hookId} can't appear in a context binding`);
  }
  const arms = Object.fromEntries(
    Object.entries(v.arms).map(([k, arm]) => [k, astToResolvable(arm)]),
  );
  return { kind: v.kind, arms, default: astToResolvable(v.default) };
};

const buildSpec = (doc: DocumentNode): ContextSpec => ({
  bindings: (doc.context?.bindings ?? []).map(b => ({
    name: b.name,
    value: astToResolvable(b.value),
  })),
});

const buildFacts = (
  gameId: string,
  executable: string,
  store: string,
  installPath: string,
): DiscoveryFacts => ({
  store,
  os: 'windows',
  arch: 'x64',
  installPath,
  executablePath: `${installPath}/${executable}`,
  // Optional discovery facts Vortex supplies at runtime — provided so games that
  // deploy to user-data roots (LocalLow/Roaming) resolve their setup dirs and
  // queryModPath instead of throwing an unbound-variable error at codegen.
  appDataRoaming: '/appdata/Roaming',
  appDataLocal: '/appdata/Local',
  appDataLocalLow: '/appdata/LocalLow',
  documents: '/documents',
  home: '/home',
});

interface Scenario {
  store: string;
  installPath: string;
  expectedSetupDirs: string[];
  expectedQueryModPath?: string;
}

const computeScenarios = (doc: DocumentNode): Scenario[] => {
  const spec = buildSpec(doc);
  const stores = doc.stores?.entries.map(e => e.id) ?? ['manual'];
  const setupDirs = doc.setup?.ensureDirs ?? [];
  const overrides = doc.tests?.scenarios ?? {};

  return stores.map(store => {
    // Use the per-store override if declared; otherwise default to a path that
    // contains the game id (so absolute-path assertions stay stable).
    const installPath = overrides[store]?.installPath ?? `/games/${doc.game.id}`;
    const facts = buildFacts(doc.game.id, doc.game.executable, store, installPath);
    const ctx = resolveContext(spec, facts);
    const expectedSetupDirs = setupDirs.map(t => interpolate(t, ctx));
    const scenario: Scenario = {
      store,
      installPath: facts.installPath,
      expectedSetupDirs,
    };
    if (doc.game.queryModPath) {
      scenario.expectedQueryModPath = interpolate(doc.game.queryModPath, ctx);
    }
    return scenario;
  });
};

export const renderLifecycleTestFile = (doc: DocumentNode): string => {
  const setupDirs = doc.setup?.ensureDirs ?? [];
  const hasSetup = setupDirs.length > 0;
  const hasQueryModPath = !!doc.game.queryModPath;
  const didDeployHook = doc.events?.didDeploy?.hookId;

  // Pre-compute every scenario at codegen time so the emitted test contains
  // literal expected values, not template strings that re-resolve at runtime.
  // Drift in either the resolver or the templates surfaces as a literal diff.
  const scenarios = (hasSetup || hasQueryModPath) ? computeScenarios(doc) : [];

  // Nothing to test — game.yaml has no setup, no queryModPath, no event hook.
  if (scenarios.length === 0 && !didDeployHook) {
    return `// AUTO-GENERATED by GDL. Do not edit by hand.
// Source: ${doc.game.span.file}
// (no lifecycle behaviour declared — empty test file)
import { describe } from 'vitest';
describe.skip(${sq(doc.game.id + ' — lifecycle (no assertions)')}, () => {});
`;
  }

  const scenarioBlocks = scenarios.map(s => `
  describe(${sq(`scenario: store=${s.store}`)}, () => {
    beforeEach(() => vi.clearAllMocks());

    ${hasSetup ? `it('setup creates the expected directories', async () => {
      const h = createFakeContext();
      main(h.context as never);
      const g = h.registered.game;
      if (!g?.setup) throw new Error('extension did not register a setup function');
      await g.setup({ path: ${sq(s.installPath)}, store: ${sq(s.store)} });
      const calls = vi.mocked(fs.ensureDirWritableAsync).mock.calls.map(c => c[0]);
${s.expectedSetupDirs.map(d => `      expect(calls).toContain(${sq(d)});`).join('\n')}
    });` : ''}

    ${s.expectedQueryModPath !== undefined ? `it('queryModPath returns the resolved path', async () => {
      const h = createFakeContext();
      main(h.context as never);
      const g = h.registered.game;
      if (!g?.setup || !g?.queryModPath) throw new Error('extension is missing setup or queryModPath');
      await g.setup({ path: ${sq(s.installPath)}, store: ${sq(s.store)} });
      expect(g.queryModPath(${sq(s.installPath)})).toBe(${sq(s.expectedQueryModPath)});
    });` : ''}
  });`).join('\n');

  // For did-deploy: spy on the user's hook export and assert that emitting
  // the event actually invokes it. Catches the GDL #6-class bug (listener
  // not wired up) and any future regression where the event name drifts.
  const eventBlock = didDeployHook ? `
describe(${sq(doc.game.id + ' — lifecycle: did-deploy hook wiring')}, () => {
  it('emitting did-deploy invokes the configured hook', async () => {
    const spy = vi.spyOn(hooks, ${sq(didDeployHook)}).mockImplementation(async () => {});
    const h = createFakeContext();
    main(h.context as never);
    await h.runOnce();
    h.emit('did-deploy', 'profile-1', []);
    await new Promise(r => setImmediate(r));
    expect(spy).toHaveBeenCalled();
  });
});` : '';

  const hookImport = didDeployHook
    ? `import * as hooks from '../src/hooks.js';\n`
    : '';

  return `// AUTO-GENERATED by GDL. Do not edit by hand.
// Source: ${doc.game.span.file}
import { describe, it, expect, beforeEach, vi } from 'vitest';
import { fs } from 'vortex-api';
import { createFakeContext } from '@gdl/runtime/testing';
import main from './extension.js';
${hookImport}
describe(${sq(doc.game.id + ' — lifecycle')}, () => {${scenarioBlocks}
});
${eventBlock}
`;
};
