// Emits `.gdl-out/templates.gen.ts`: a vitest-runnable test file that walks
// every ${expr} the extension uses (modtype paths, toolbar action targets,
// queryModPath, setup.ensureDirs) and resolves each one under every store
// branch declared in `stores:`. Any unbound variable, missing branch arm, or
// cycle surfaces as a named failure pointing at the specific template.
//
// Downstream extensions get this guard automatically — no per-game test code
// required. The Subnautica 2 1.1.0 unbound-`pakModsPath` regression would have
// failed this gate immediately if it had existed at the time.

import type { DocumentNode, ValueNode } from '../parser/ast.js';
import { sq } from './emit.js';

// Re-implementation of the binding/value rendering used by emit.ts. Kept
// local to avoid coupling the two emitters; the rendered shape is small.
const renderValueNode = (v: ValueNode): string => {
  if (v.kind === 'literal') return `{ kind: 'literal', raw: ${sq(String(v.raw))} }`;
  if (v.kind === 'interpolated') return `{ kind: 'interpolated', template: ${sq(v.template)} }`;
  if (v.kind === 'hookRef') {
    // hookRefs are filtered out before this point in the emit pipeline.
    throw new Error(`hookRef ${v.hookId} not legal in resolved context`);
  }
  const arms = Object.entries(v.arms)
    .map(([k, arm]) => `${sq(k)}: ${renderValueNode(arm)}`)
    .join(', ');
  return `{ kind: ${sq(v.kind)}, arms: { ${arms} }, default: ${renderValueNode(v.default)} }`;
};

interface TemplateRef {
  source: string;   // "modType:pak.path", "toolbarAction:open-mods.target", etc.
  template: string;
}

const collectTemplates = (doc: DocumentNode): TemplateRef[] => {
  const out: TemplateRef[] = [];

  // ModType paths — branch arms unwrapped to test every arm's template.
  for (const mt of doc.modTypes ?? []) {
    pushFromValueNode(out, `modType:${mt.id}.path`, mt.path);
  }

  // Toolbar action targets (already plain strings).
  for (const a of doc.toolbarActions ?? []) {
    out.push({ source: `toolbarAction:${a.id}.target`, template: a.target.template });
  }

  // queryModPath, if set.
  if (doc.game.queryModPath) {
    out.push({ source: 'game.queryModPath', template: doc.game.queryModPath });
  }

  // setup.ensureDirs entries.
  for (const tpl of doc.setup?.ensureDirs ?? []) {
    out.push({ source: `setup.ensureDirs[${tpl}]`, template: tpl });
  }

  return out;
};

const pushFromValueNode = (out: TemplateRef[], source: string, v: ValueNode): void => {
  if (v.kind === 'literal' || v.kind === 'hookRef') return;
  if (v.kind === 'interpolated') {
    out.push({ source, template: v.template });
    return;
  }
  // Branch: walk every arm plus default, so we cover the templates the runtime
  // might pick under each scenario.
  for (const [arm, value] of Object.entries(v.arms)) {
    pushFromValueNode(out, `${source}[${arm}]`, value);
  }
  pushFromValueNode(out, `${source}[default]`, v.default);
};

export const renderTemplatesTestFile = (doc: DocumentNode): string => {
  const storeIds = (doc.stores?.entries ?? []).map(e => e.id);
  // Always test at least one scenario; if no stores are declared, run a
  // generic 'manual' fixture so context-only bindings still get coverage.
  const scenarios = storeIds.length > 0 ? storeIds : ['manual'];

  const bindings = (doc.context?.bindings ?? [])
    .map(b => `    { name: ${sq(b.name)}, value: ${renderValueNode(b.value)} }`)
    .join(',\n');

  const templates = collectTemplates(doc);
  const templatesLines = templates
    .map(t => `  { source: ${sq(t.source)}, template: ${sq(t.template)} }`)
    .join(',\n');

  // If there's nothing to check, emit an empty (always-pass) file rather than
  // skipping codegen — keeps the file path stable for vitest globs.
  const noTemplates = templates.length === 0;

  return `// AUTO-GENERATED by GDL. Do not edit by hand.
// Source: ${doc.game.span.file}
import { describe, it, expect } from 'vitest';
import { resolveContext, interpolate, type ContextSpec, type DiscoveryFacts } from '@gdl/runtime';

const CONTEXT_SPEC: ContextSpec = {
  bindings: [
${bindings}
  ],
};

const TEMPLATES: { source: string; template: string }[] = [
${templatesLines}
];

const SCENARIOS = [${scenarios.map(sq).join(', ')}] as const;

describe(${sq(doc.game.id + ' — template resolution')}, () => {
  for (const store of SCENARIOS) {
    describe(\`scenario: store=\${store}\`, () => {
      const facts: DiscoveryFacts = {
        store,
        os: 'windows',
        arch: 'x64',
        installPath: ${sq('/games/' + doc.game.id)},
        executablePath: ${sq('/games/' + doc.game.id + '/' + doc.game.executable)},
        // Optional discovery facts Vortex supplies at runtime. Provided here so
        // templates that legitimately reference user-data roots (e.g. mods that
        // deploy to LocalLow) resolve instead of tripping the unbound-var guard.
        appDataRoaming: '/appdata/Roaming',
        appDataLocal: '/appdata/Local',
        appDataLocalLow: '/appdata/LocalLow',
        documents: '/documents',
        home: '/home',
      };

      it('context bindings resolve without unbound variables', () => {
        // resolveContext throws on cycles and unbound vars; reaching the
        // assert means every binding's value was resolvable for this branch.
        const ctx = resolveContext(CONTEXT_SPEC, facts);
        for (const b of CONTEXT_SPEC.bindings) {
          expect(ctx).toHaveProperty(b.name);
          expect(typeof ctx[b.name]).toMatch(/^(string|number|boolean)$/);
        }
      });

      ${noTemplates ? '' : `it('every template referenced from setup/modtypes/actions resolves', () => {
        const ctx = resolveContext(CONTEXT_SPEC, facts);
        const failures: string[] = [];
        for (const { source, template } of TEMPLATES) {
          try {
            interpolate(template, ctx);
          } catch (err) {
            failures.push(\`[\${source}] "\${template}" — \${(err as Error).message}\`);
          }
        }
        expect(failures, failures.join('\\\\n')).toEqual([]);
      });`}
    });
  }
});
`;
};
