import type { DocumentNode, TestCaseNode } from '../parser/ast.js';
import { sq } from './emit.js';

const renderCase = (c: TestCaseNode): string => {
  const expectObj = c.expect
    ? `{
      ${c.expect.matched !== undefined ? `matched: ${sq(c.expect.matched)},` : ''}
      ${c.expect.modType !== undefined ? `modType: ${sq(c.expect.modType)},` : ''}
      ${c.expect.plan    !== undefined ? `plan: [${c.expect.plan.map(sq).join(', ')}],` : ''}
    }`
    : '{}';

  const archive = c.archive.map(p => sq(p)).join(', ');

  return `  it(${sq(c.name)}, () => {
    const archive = [${archive}];
    const ctx = { archivePaths: archive, vars: flatVars };
    let matchedId: string | undefined;
    let plan: InstallInstruction[] = [];
    // Vortex picks the installer with the lowest priority number when multiple match.
    // Sort by priority so the harness matches that runtime semantic.
    const sortedRules = [...rules].sort((a, b) => a.priority - b.priority);
    for (const rule of sortedRules) {
      const result = buildInstallPlan(rule, archive, ctx);
      if (result.length > 0) {
        matchedId = rule.id;
        plan = result;
        break;
      }
    }
    if (!matchedId) throw new Error('no installer matched');
    const ar = assertPlan(plan, matchedId, ${expectObj});
    if (!ar.ok) throw new Error(ar.message);
  });
`;
};

export const renderTestsFile = (doc: DocumentNode): string => {
  if (!doc.tests || doc.tests.cases.length === 0) return '';

  const cases = doc.tests.cases.map(renderCase).join('\n');

  // Pre-resolve context bindings. Branch tags fall back to the `default` arm.
  // Tests assume windows/steam baseline; refine the context if a test needs a specific store.
  const contextBindings = (doc.context?.bindings ?? [])
    .map(b => {
      if (b.value.kind === 'literal')      return `  ${sq(b.name)}: ${JSON.stringify(String(b.value.raw))}`;
      if (b.value.kind === 'interpolated') return `  ${sq(b.name)}: ${sq(b.value.template)}`;
      // For branches in tests, pick the default arm if it's literal/interpolated.
      const arm = b.value.kind === 'storeBranch' || b.value.kind === 'osBranch' || b.value.kind === 'versionBranch'
        ? b.value.default
        : undefined;
      if (arm?.kind === 'literal')      return `  ${sq(b.name)}: ${JSON.stringify(String(arm.raw))}`;
      if (arm?.kind === 'interpolated') return `  ${sq(b.name)}: ${sq(arm.template)}`;
      return `  ${sq(b.name)}: ${sq('<branch — refine in test fixture>')}`;
    })
    .join(',\n');

  return `// AUTO-GENERATED by GDL. Do not edit by hand.
import { describe, it } from 'vitest';
import { buildInstallPlan, type InstallInstruction, assertPlan } from '../gdl/src/runtime/index.js';
import { rules } from './installers.gen.js';

// Synthetic test context: literal/interpolated bindings resolved with placeholder facts.
const resolvedVars: Record<string, string> = {
  store: 'steam',
  os: 'windows',
  arch: 'x64',
  installPath: '/games/Hello',
  executablePath: '/games/Hello/${doc.game.executable}',
${contextBindings}${contextBindings ? ',' : ''}
};

// Pre-interpolate \${name} placeholders so they resolve at test time.
function interpolateVars(obj: Record<string, string>): Record<string, string> {
  const out: Record<string, string> = { ...obj };
  for (let i = 0; i < 10; i++) {
    let changed = false;
    for (const k of Object.keys(out)) {
      const replaced = (out[k] as string).replace(/\\\${([a-zA-Z_][a-zA-Z0-9_]*)}/g, (_m, name) =>
        out[name] !== undefined ? (out[name] as string) : '\${' + name + '}'
      );
      if (replaced !== out[k]) { out[k] = replaced; changed = true; }
    }
    if (!changed) break;
  }
  return out;
}

const flatVars = interpolateVars(resolvedVars);

describe(${sq(doc.game.id + ' — generated tests')}, () => {
${cases}});
`;
};
